-- AlterEnum: เพิ่ม RUN_AN_ERRAND ในประเภทการลา
ALTER TABLE `leaves` MODIFY COLUMN `type` ENUM('SICK', 'PERSONAL', 'VACATION', 'MATERNITY', 'ORDINATION', 'EARLY_LEAVE', 'RUN_AN_ERRAND', 'OTHER') NOT NULL;
